version = "5.1"
globals = {
    "ARG",
    "C_Timer",
    "CreateFrame",
    "debugstack",
    "geterrorhandler",
    "GetCallstackHeight",
    "GetErrorCallstackHeight",
    "GetRealZoneText",
    "GetTime",
    "hooksecurefunc",
    "Loudmouth",
    "NUM_CHAT_WINDOWS",
    "Slashes",
    "SendChatMessage",
    "SlashCmdList",
    "UIParent",
    "UnitClass",
    "UnitGender",
    "UnitRace",
    "wipe",
    "seterrorhandler",
    "SLASH_LOUDMOUTH1",
    "SLASH_LOUDMOUTH2",
    "SLASH_LOUDMOUTHCOPYERRORS1",
    "SLASH_LOUDMOUTHCOPYERRORS2",
}
