-- World of Warcraft Classic Era location metadata.
-- Canonical map IDs and names are from Blizzard's UiMap/AreaTable data for
-- Classic Era. Subzones are parent-scoped because many names occur in more
-- than one zone.
Loudmouth = Loudmouth or {}

Loudmouth.ClassicZones = {
    -- Kalimdor
    [1411] = { name = "Durotar", continent = "Kalimdor" },
    [1412] = { name = "Mulgore", continent = "Kalimdor" },
    [1413] = { name = "The Barrens", continent = "Kalimdor" },
    [1438] = { name = "Teldrassil", continent = "Kalimdor" },
    [1439] = { name = "Darkshore", continent = "Kalimdor" },
    [1440] = { name = "Ashenvale", continent = "Kalimdor" },
    [1441] = { name = "Thousand Needles", continent = "Kalimdor" },
    [1442] = { name = "Stonetalon Mountains", continent = "Kalimdor" },
    [1443] = { name = "Desolace", continent = "Kalimdor" },
    [1444] = { name = "Feralas", continent = "Kalimdor" },
    [1445] = { name = "Dustwallow Marsh", continent = "Kalimdor" },
    [1446] = { name = "Tanaris", continent = "Kalimdor" },
    [1447] = { name = "Azshara", continent = "Kalimdor" },
    [1448] = { name = "Felwood", continent = "Kalimdor" },
    [1449] = { name = "Un'Goro Crater", continent = "Kalimdor" },
    [1450] = { name = "Moonglade", continent = "Kalimdor" },
    [1451] = { name = "Silithus", continent = "Kalimdor" },
    [1452] = { name = "Winterspring", continent = "Kalimdor" },
    [1454] = { name = "Orgrimmar", continent = "Kalimdor", kind = "city" },
    [1456] = { name = "Thunder Bluff", continent = "Kalimdor", kind = "city" },
    [1457] = { name = "Darnassus", continent = "Kalimdor", kind = "city" },

    -- Eastern Kingdoms
    [1416] = { name = "Alterac Mountains", continent = "Eastern Kingdoms" },
    [1417] = { name = "Arathi Highlands", continent = "Eastern Kingdoms" },
    [1418] = { name = "Badlands", continent = "Eastern Kingdoms" },
    [1419] = { name = "Blasted Lands", continent = "Eastern Kingdoms" },
    [1420] = { name = "Tirisfal Glades", continent = "Eastern Kingdoms" },
    [1421] = { name = "Silverpine Forest", continent = "Eastern Kingdoms" },
    [1422] = { name = "Western Plaguelands", continent = "Eastern Kingdoms" },
    [1423] = { name = "Eastern Plaguelands", continent = "Eastern Kingdoms" },
    [1424] = { name = "Hillsbrad Foothills", continent = "Eastern Kingdoms" },
    [1425] = { name = "The Hinterlands", continent = "Eastern Kingdoms" },
    [1426] = { name = "Dun Morogh", continent = "Eastern Kingdoms" },
    [1427] = { name = "Searing Gorge", continent = "Eastern Kingdoms" },
    [1428] = { name = "Burning Steppes", continent = "Eastern Kingdoms" },
    [1429] = { name = "Elwynn Forest", continent = "Eastern Kingdoms" },
    [1430] = { name = "Deadwind Pass", continent = "Eastern Kingdoms" },
    [1431] = { name = "Duskwood", continent = "Eastern Kingdoms" },
    [1432] = { name = "Loch Modan", continent = "Eastern Kingdoms" },
    [1433] = { name = "Redridge Mountains", continent = "Eastern Kingdoms" },
    [1434] = { name = "Stranglethorn Vale", continent = "Eastern Kingdoms" },
    [1435] = { name = "Swamp of Sorrows", continent = "Eastern Kingdoms" },
    [1436] = { name = "Westfall", continent = "Eastern Kingdoms" },
    [1437] = { name = "Wetlands", continent = "Eastern Kingdoms" },
    [1453] = { name = "Stormwind City", continent = "Eastern Kingdoms", kind = "city" },
    [1455] = { name = "Ironforge", continent = "Eastern Kingdoms", kind = "city" },
    [1458] = { name = "Undercity", continent = "Eastern Kingdoms", kind = "city" },

    -- Battleground maps
    [1459] = { name = "Alterac Valley", continent = "Battleground", kind = "battleground" },
    [1460] = { name = "Warsong Gulch", continent = "Battleground", kind = "battleground" },
    [1461] = { name = "Arathi Basin", continent = "Battleground", kind = "battleground" },
}

-- Instances are kept separate because GetRealZoneText() can return these names,
-- but they are not outdoor UiMap zone records.
Loudmouth.ClassicInstances = {
    [2437] = "Ragefire Chasm",
    [718] = "Wailing Caverns",
    [1581] = "The Deadmines",
    [209] = "Shadowfang Keep",
    [719] = "Blackfathom Deeps",
    [717] = "The Stockade",
    [721] = "Gnomeregan",
    [491] = "Razorfen Kraul",
    [796] = "Scarlet Monastery",
    [722] = "Razorfen Downs",
    [1337] = "Uldaman",
    [1176] = "Zul'Farrak",
    [2100] = "Maraudon",
    [1477] = "The Temple of Atal'Hakkar",
    [1584] = "Blackrock Depths",
    [1583] = "Blackrock Spire",
    [2557] = "Dire Maul",
    [2057] = "Scholomance",
    [2017] = "Stratholme",
    [2717] = "Molten Core",
    [2159] = "Onyxia's Lair",
    [2677] = "Blackwing Lair",
    [1977] = "Zul'Gurub",
    [3429] = "Ruins of Ahn'Qiraj",
    [3428] = "Ahn'Qiraj",
    [3456] = "Naxxramas",
}

-- Common GetSubZoneText() values, grouped by their outdoor parent. The parent
-- key prevents ambiguous names such as Dun Algaz and The Great Sea from being
-- assigned to the wrong zone.
Loudmouth.ClassicSubzones = {
    ["Durotar"] = {
        "Valley of Trials", "The Den", "Sen'jin Village", "Echo Isles", "Razor Hill",
        "Tiragarde Keep", "Skull Rock", "Orgrimmar", "Thunder Ridge", "Drygulch Ravine",
        "Dustwind Cave", "Burning Blade Coven", "Deadeye Shore", "Southfury River",
    },
    ["Mulgore"] = {
        "Camp Narache", "Red Cloud Mesa", "Bloodhoof Village", "Thunder Bluff", "The Golden Plains",
        "The Rolling Plains", "Palemane Rock", "The Venture Co. Mine", "Red Rocks", "Wildmane Water Well",
        "Winterhoof Water Well", "Thunderhorn Water Well", "Bael'dun Digsite", "Windfury Ridge",
    },
    ["The Barrens"] = {
        "The Crossroads", "Ratchet", "Camp Taurajo", "The Sludge Fen", "The Forgotten Pools",
        "Lushwater Oasis", "The Stagnant Oasis", "Dreadmist Peak", "Dreadmist Den", "The Dry Hills",
        "Thorn Hill", "The Merchant Coast", "Northwatch Hold", "Bael Modan", "Razorfen Kraul",
        "Razorfen Downs", "The Great Lift", "Blackthorn Ridge", "Agama'gor", "Field of Giants",
    },
    ["Teldrassil"] = {
        "Shadowglen", "Aldrassil", "Dolanaar", "Darnassus", "Lake Al'Ameth", "Starbreeze Village",
        "Ban'ethil Hollow", "Ban'ethil Barrow Den", "The Cleft", "The Oracle Glade", "Wellspring Lake",
        "Pools of Arlithrien", "Gnarlpine Hold", "Rut'theran Village", "Fel Rock", "Shadowthread Cave",
    },
    ["Darkshore"] = {
        "Auberdine", "Ruins of Mathystra", "Bashal'Aran", "Ameth'Aran", "The Master's Glaive",
        "Blackwood Den", "Cliffspring River", "Cliffspring Falls", "Cliffspring Hollow", "Mist's Edge",
        "Twilight Vale", "Remtravel's Excavation", "Grove of the Ancients", "The Long Wash",
    },
    ["Ashenvale"] = {
        "Astranaar", "Maestra's Post", "The Zoram Strand", "Zoram'gar Outpost", "Warsong Lumber Camp",
        "Silverwind Refuge", "Raynewood Retreat", "Forest Song", "Satyrnaar", "Xavian", "Night Run",
        "Felfire Hill", "Demon Fall Canyon", "Demon Fall Ridge", "Bough Shadow", "The Howling Vale",
        "The Dor'Danil Barrow Den", "Fire Scar Shrine", "Splintertree Post", "The Ruins of Stardust",
    },
    ["Thousand Needles"] = {
        "Freewind Post", "The Great Lift", "Highperch", "Darkcloud Pinnacle", "The Screeching Canyon",
        "The Shimmering Flats", "Mirage Raceway", "Rustmaul Dig Site", "Splithoof Crag", "Camp E'thok",
        "Windbreak Canyon", "The Weathered Nook", "Thalanaar", "Roguefeather Den",
    },
    ["Stonetalon Mountains"] = {
        "Stonetalon Peak", "Sun Rock Retreat", "Windshear Crag", "Windshear Mine", "The Charred Vale",
        "Mirkfallon Lake", "Cragpool Lake", "Boulderslide Ravine", "Boulderslide Cavern", "Webwinder Path",
        "Sishir Canyon", "Malaka'jin", "Grimtotem Post", "The Talon Den", "Greatwood Vale",
    },
    ["Desolace"] = {
        "Nijel's Point", "Shadowprey Village", "Ghost Walker Post", "Kodo Graveyard", "Valley of Bones",
        "Mannoroc Coven", "Sargeron", "Thunder Axe Fortress", "Shadowbreak Ravine", "Tethris Aran",
        "Maraudon", "The Wicked Grotto", "Foulspore Cavern", "Gelkis Village", "Magram Village",
        "Sar'theris Strand", "Ethel Rethor", "Ranazjar Isle", "Kormek's Hut",
    },
    ["Feralas"] = {
        "Feathermoon Stronghold", "Camp Mojache", "Dire Maul", "The Twin Colossals", "The Forgotten Coast",
        "Isle of Dread", "Ruins of Feathermoon", "Feral Scar Vale", "The Writhing Deep", "Lariss Pavilion",
        "The Ruins of Solarsal", "Darkmist Ruins", "Ravenwind", "Dream Bough", "Grimtotem Compound",
        "Gordunni Outpost", "Gordunni Compound", "Woodpaw Hills", "Frayfeather Highlands",
    },
    ["Dustwallow Marsh"] = {
        "Theramore Isle", "Brackenwall Village", "Witch Hill", "Darkmist Cavern", "Bloodfen Burrow",
        "The Dragonmurk", "Wyrmbog", "The Den of Flame", "Onyxia's Lair", "Alcaz Island",
        "The Shady Rest Inn", "Sentry Point", "North Point Tower", "Beezil's Wreck", "Tidefury Cove",
    },
    ["Tanaris"] = {
        "Gadgetzan", "Steamwheedle Port", "Zul'Farrak", "The Noxious Lair", "The Gaping Chasm",
        "Caverns of Time", "Land's End Beach", "Southmoon Ruins", "Eastmoon Ruins", "Dunemaul Compound",
        "Lost Rigger Cove", "Abyssal Sands", "Thistleshrub Valley", "The Rustmaul Dig Site", "Waterspring Field",
    },
    ["Azshara"] = {
        "Talrendis Point", "Valormok", "Ruins of Eldarath", "The Shattered Strand", "Bitter Reaches",
        "Bay of Storms", "Hetaera's Clutch", "Temple of Arkkoran", "Tower of Eldara", "Legash Encampment",
        "Thalassian Base Camp", "Shadowsong Shrine", "Lake Mennar", "Ravencrest Monument", "Forlorn Ridge",
    },
    ["Felwood"] = {
        "Emerald Sanctuary", "Bloodvenom Post", "Talonbranch Glade", "Jaedenar", "Shadow Hold",
        "Shrine of the Deceiver", "Shatter Scar Vale", "Bloodvenom River", "Bloodvenom Falls",
        "Irontree Cavern", "Jadefire Glen", "Jadefire Run", "Morlos'Aran", "Ruins of Constellas",
        "Deadwood Village", "Felpaw Village", "Jadefire Run", "Wildheart Point",
    },
    ["Un'Goro Crater"] = {
        "Marshal's Refuge", "The Marshlands", "The Slithering Scar", "Fire Plume Ridge", "Terror Run",
        "The Screaming Reaches", "The Roiling Gardens", "Ironstone Plateau", "Fungal Rock", "Golakka Hot Springs",
        "Lakkari Tar Pits", "Mossy Pile", "The Shaper's Terrace", "The Scarab Wall",
    },
    ["Moonglade"] = {
        "Nighthaven", "Lake Elune'ara", "Shrine of Remulos", "Stormrage Barrow Dens",
    },
    ["Silithus"] = {
        "Cenarion Hold", "Twilight Base Camp", "Twilight Post", "Twilight Outpost", "Twilight's Run",
        "The Crystal Vale", "Hive'Ashi", "Hive'Zora", "Hive'Regal", "The Swarming Pillar",
        "Bones of Grakkarond", "Southwind Village", "Valor's Rest", "The Scarab Wall", "Bronzebeard Encampment",
    },
    ["Winterspring"] = {
        "Everlook", "Frostsaber Rock", "Starfall Village", "Lake Kel'Theril", "Mazthoril", "Owl Wing Thicket",
        "Frostwhisper Gorge", "Darkwhisper Gorge", "Ban'Thallow Barrow Den", "Moon Horror Den",
        "Timbermaw Post", "Winterfall Village", "Ice Thistle Hills", "The Hidden Grove", "Frostfire Hot Springs",
    },
    ["Orgrimmar"] = { "Valley of Strength", "Valley of Spirits", "Valley of Wisdom", "Valley of Honor", "The Drag", "Cleft of Shadow" },
    ["Thunder Bluff"] = { "Lower Rise", "Middle Rise", "High Rise", "Hunter Rise", "Elder Rise", "Spirit Rise" },
    ["Darnassus"] = { "Cenarion Enclave", "Craftsmen's Terrace", "Warrior's Terrace", "Temple Gardens", "The Temple of the Moon", "Tradesmen's Terrace" },

    ["Alterac Mountains"] = {
        "Chillwind Point", "Dalaran", "Lordamere Lake", "Crushridge Hold", "The Uplands", "Gavin's Naze",
        "Sofera's Naze", "Gallows' Corner", "Dandred's Fold", "Strahnbrad", "Ruins of Alterac", "Growless Cave",
    },
    ["Arathi Highlands"] = {
        "Refuge Pointe", "Hammerfall", "Stromgarde Keep", "Faldir's Cove", "Boulderfist Hall", "Witherbark Village",
        "Go'Shek Farm", "Dabyrie's Farmstead", "Northfold Manor", "Circle of East Binding", "Circle of West Binding",
        "Circle of Inner Binding", "Circle of Outer Binding", "Thandol Span", "Thoradin's Wall",
    },
    ["Badlands"] = {
        "Kargath", "Uldaman", "Angor Fortress", "Hammertoe's Digsite", "The Maker's Terrace",
        "Dustbelch Grotto", "Agmond's End", "Camp Cagg", "Apocryphan's Rest", "Lethlor Ravine",
        "Valley of Fangs", "Mirage Flats", "The Dustbowl",
    },
    ["Blasted Lands"] = {
        "Nethergarde Keep", "Dreadmaul Hold", "Dreadmaul Post", "The Dark Portal", "The Tainted Scar",
        "Altar of Storms", "Serpent's Coil", "Rise of the Defiler", "The Red Reaches", "The Dark Portal",
    },
    ["Tirisfal Glades"] = {
        "Deathknell", "Brill", "Ruins of Lordaeron", "Agamand Mills", "Agamand Family Crypt",
        "Whispering Gardens", "Garren's Haunt", "Cold Hearth Manor", "Nightmare Vale", "Venomweb Vale",
        "Shadow Grave", "Night Web's Hollow", "Solliden Farmstead", "Brightwater Lake", "Crusader Outpost",
        "Scarlet Watch Post", "Scarlet Monastery", "The Bulwark", "Balnir Farmstead",
    },
    ["Silverpine Forest"] = {
        "The Sepulcher", "Pyrewood Village", "Shadowfang Keep", "Fenris Isle", "Fenris Keep",
        "The Skittering Dark", "Beren's Peril", "The Dead Field", "The Ivar Patch", "Deep Elem Mine",
        "Ambermill", "The Decrepit Ferry", "North Tide's Run", "The Greymane Wall", "Valgan's Field",
    },
    ["Western Plaguelands"] = {
        "Chillwind Camp", "The Bulwark", "Ruins of Andorhal", "School of Necromancy", "Sorrow Hill",
        "The Weeping Cave", "Felstone Field", "Dalson's Tears", "Gahrron's Withering", "The Writhing Haunt",
        "Caer Darrow", "Hearthglen", "The Uplands", "Northridge Lumber Camp", "Darrowmere Lake",
    },
    ["Eastern Plaguelands"] = {
        "Light's Hope Chapel", "The Fungal Vale", "The Marris Stead", "The Undercroft", "Darrowshire",
        "Corin's Crossing", "The Noxious Glade", "Zul'Mashar", "Plaguewood", "Scourgehold", "Stratholme",
        "Pestilent Scar", "The Infectis Scar", "Terrorweb Tunnel", "Terrordale", "Northdale", "Blackwood Lake",
        "Quel'Lithien Lodge", "The Quel'Danil Lodge", "Eastwall Tower", "Crown Guard Tower", "Northpass Tower",
    },
    ["Hillsbrad Foothills"] = {
        "Southshore", "Tarren Mill", "Durnholde Keep", "Dun Garok", "Hillsbrad Fields", "Hillsbrad Foothill",
        "Purgation Isle", "Azurelode Mine", "Nethander Stead", "Darrow Hill", "Thoradin's Wall", "The Headland",
    },
    ["The Hinterlands"] = {
        "Aerie Peak", "Wildhammer Keep", "Revantusk Village", "The Altar of Zul", "Jintha'Alor", "Shadra'Alor",
        "The Overlook Cliffs", "Skulk Rock", "Seradane", "The Creeping Ruin", "Agol'watha", "Quel'Danil Lodge",
        "Valorwind Lake", "The Twin Colossals", "Zun'watha", "The Hinterlands",
    },
    ["Dun Morogh"] = {
        "Anvilmar", "Kharanos", "Coldridge Valley", "Coldridge Pass", "Chill Breeze Valley", "Gnomeregan",
        "Gol'Bolar Quarry", "The Grizzled Den", "Brewnall Village", "Steelgrill's Depot", "Ironband's Compound",
        "Amberstill Ranch", "Shimmer Ridge", "The Tundrid Hills", "South Gate Pass", "South Gate Outpost",
        "North Gate Pass", "North Gate Outpost", "Gates of Ironforge", "Thunderbrew Distillery", "Iceflow Lake",
    },
    ["Searing Gorge"] = {
        "Thorium Point", "The Cauldron", "The Slag Pit", "Blackrock Mountain", "Blackchar Cave",
        "Grimesilt Dig Site", "Dustfire Valley", "Firewatch Ridge", "Tanner Camp", "Sea of Cinders",
    },
    ["Burning Steppes"] = {
        "Morgan's Vigil", "Flame Crest", "Blackrock Mountain", "Ruins of Thaurissan", "Dreadmaul Rock",
        "Blackrock Stronghold", "Altar of Storms", "The Pillar of Ash", "Draco'dar", "Terror Wing Path",
    },
    ["Elwynn Forest"] = {
        "Northshire Valley", "Northshire Abbey", "Goldshire", "Eastvale Logging Camp", "Crystal Lake",
        "Stone Cairn Lake", "Fargodeep Mine", "Jasperlode Mine", "Forest's Edge", "Brackwell Pumpkin Patch",
        "Jerod's Landing", "Ridgepoint Tower", "Tower of Azora", "Westbrook Garrison", "The Maclure Vineyards",
    },
    ["Deadwind Pass"] = {
        "Deadwind Ravine", "Deadman's Crossing", "Ariden's Camp", "The Vice", "Karazhan", "Morgan's Plot",
        "The Master's Cellar", "Grosh'gok Compound", "Sleeping Gorge",
    },
    ["Duskwood"] = {
        "Darkshire", "Raven Hill", "Raven Hill Cemetery", "Tranquil Gardens Cemetery", "Forlorn Rowe",
        "Dawning Wood Catacombs", "The Rotting Orchard", "Beggar's Haunt", "Addle's Stead",
        "The Yorgen Farmstead", "Twilight Grove", "Manor Mistmantle", "Roland's Doom", "Vul'Gol Ogre Mound",
        "The Darkened Bank", "Brightwood Grove", "The Hushed Bank", "Deadwind Pass",
    },
    ["Loch Modan"] = {
        "Thelsamar", "Ironband's Excavation Site", "Algaz Gate", "Stonewrought Dam", "Silver Stream Mine",
        "Dun Algaz", "North Gate Pass", "South Gate Pass", "Stonesplinter Valley", "Valley of Kings",
        "Algaz Station", "Stoutlager Inn", "Mo'grosh Stronghold", "The Loch", "Grizzlepaw Ridge",
    },
    ["Redridge Mountains"] = {
        "Lakeshire", "Lake Everstill", "Stonewatch", "Stonewatch Falls", "Stonewatch Keep", "Tower of Ilgalar",
        "Render's Camp", "Render's Valley", "Render's Rock", "Alther's Mill", "Three Corners", "Lakeridge Highway",
        "Rethban Caverns", "Galardell Valley", "The Darkened Bank",
    },
    ["Stranglethorn Vale"] = {
        "Booty Bay", "Grom'gol Base Camp", "Rebel Camp", "Nesingwary's Expedition", "Kurzen's Compound",
        "The Vile Reef", "Mizjah Ruins", "Bal'lal Ruins", "Balia'mah Ruins", "Ziata'jai Ruins", "Ruins of Zul'Kunda",
        "Ruins of Zul'Mamwe", "Zul'Gurub", "Crystalvein Mine", "Venture Co. Base Camp", "The Cape of Stranglethorn",
        "The Savage Coast", "Wild Shore", "Janeiro's Point", "The Arena", "Mosh'Ogg Ogre Mound",
    },
    ["Swamp of Sorrows"] = {
        "Stonard", "The Harborage", "Pool of Tears", "Sunken Temple", "Fallow Sanctuary", "Misty Valley",
        "Itharius's Cave", "Stagalbog Cave", "Stagalbog", "Splinterspear Junction", "Sorrowmurk", "The Shifting Mire",
    },
    ["Westfall"] = {
        "Sentinel Hill", "Moonbrook", "The Deadmines", "Furlbrow's Pumpkin Farm", "Saldean's Farm",
        "Alexston Farmstead", "Jangolode Mine", "Gold Coast Quarry", "The Dagger Hills", "Longshore",
        "The Raging Chasm", "The Dust Plains", "Demont's Place", "Westfall Lighthouse",
    },
    ["Wetlands"] = {
        "Menethil Harbor", "Whelgar's Excavation Site", "Dun Modr", "Ironbeard's Tomb", "Dun Algaz",
        "Thandol Span", "Direforge Hill", "Grim Batol", "Dragonmaw Gates", "Bluegill Marsh", "The Green Belt",
        "Mosshide Fen", "Sundown Marsh", "The Lost Fleet", "Raptor Ridge", "Black Channel Marsh",
    },
    ["Stormwind City"] = {
        "Trade District", "Old Town", "Mage Quarter", "Dwarven District", "Cathedral Square", "The Park",
        "Stormwind Keep", "Valley of Heroes", "The Canals", "The Stockade", "The Slaughtered Lamb",
    },
    ["Ironforge"] = {
        "The Great Forge", "The Military Ward", "Hall of Explorers", "The Forlorn Cavern", "The Mystic Ward",
        "Tinker Town", "The High Seat", "The Library", "Hall of Arms", "Vault of Ironforge", "Old Ironforge",
    },
    ["Undercity"] = {
        "Ruins of Lordaeron", "The Apothecarium", "Magic Quarter", "Rogues' Quarter", "War Quarter",
        "Royal Quarter", "Sewers", "Canals", "Trade Quarter",
    },
    ["Alterac Valley"] = {
        "Dun Baldar", "Frostwolf Keep", "Field of Strife", "Iceblood Garrison", "Stonehearth Outpost",
        "Stormpike Graveyard", "Frostwolf Graveyard", "Snowfall Graveyard", "Icewing Bunker", "Tower Point",
    },
    ["Warsong Gulch"] = { "Silverwing Hold", "Warsong Lumber Mill" },
    ["Arathi Basin"] = { "Trollbane Hall", "Defilers' Den", "Stables", "Blacksmith", "Farm", "Lumber Mill", "Gold Mine" },
    ["Gnomeregan"] = {
        "Train Depot", "Loading Room", "The Clean Zone", "The Dormitory", "The Hall of Gears",
        "Engineering Labs", "Launch Bay", "The Clockwerk Run", "Tinkers' Court",
    },
    ["Uldaman"] = { "Hall of the Keepers", "Khaz'Goroth's Seat", "The Map Chamber", "The Stone Vault", "Temple of the Keepers" },
}

-- Aliases normalize values seen in old personality files and common variants.
Loudmouth.ZoneAliases = {
    ["Ironforge"] = { "City of Ironforge", "Iron Forge" },
    ["Stormwind City"] = { "Stormwind" },
    ["The Hinterlands"] = { "Hinterlands" },
    ["The Deadmines"] = { "Deadmines" },
    ["The Stockade"] = { "Stockade", "Stormwind Stockade" },
    ["The Temple of Atal'Hakkar"] = { "Sunken Temple", "Temple of Atal'Hakkar" },
    ["Ahn'Qiraj"] = { "Temple of Ahn'Qiraj" },
}

-- Strength: 3 = homeland/capital, 2 = major culture/settlement, 1 = localized
-- presence, expedition, or historical site.
Loudmouth.ZoneRaceMetadata = {
    ["Durotar"] = { orc = 3, troll = 3 },
    ["Mulgore"] = { tauren = 3, dwarf = 1 },
    ["The Barrens"] = { orc = 2, tauren = 2, dwarf = 1 },
    ["Teldrassil"] = { nightelf = 3 },
    ["Darkshore"] = { nightelf = 2 },
    ["Ashenvale"] = { nightelf = 2, orc = 2 },
    ["Thousand Needles"] = { tauren = 2, gnome = 1, dwarf = 1 },
    ["Stonetalon Mountains"] = { tauren = 1, nightelf = 1 },
    ["Desolace"] = { tauren = 1, nightelf = 1 },
    ["Feralas"] = { nightelf = 2, tauren = 1 },
    ["Dustwallow Marsh"] = { human = 2, dwarf = 1, orc = 1 },
    ["Tanaris"] = { goblin = 2, troll = 2 },
    ["Azshara"] = { nightelf = 2 },
    ["Felwood"] = { nightelf = 2 },
    ["Moonglade"] = { nightelf = 2, tauren = 1 },
    ["Silithus"] = { dwarf = 1 },
    ["Orgrimmar"] = { orc = 3, troll = 2 },
    ["Thunder Bluff"] = { tauren = 3 },
    ["Darnassus"] = { nightelf = 3 },
    ["Alterac Mountains"] = { human = 2 },
    ["Arathi Highlands"] = { human = 2, troll = 1 },
    ["Badlands"] = { dwarf = 1 },
    ["Blasted Lands"] = { human = 1, orc = 1 },
    ["Tirisfal Glades"] = { forsaken = 3, human = 1 },
    ["Silverpine Forest"] = { forsaken = 2, human = 1 },
    ["Western Plaguelands"] = { human = 2, forsaken = 2 },
    ["Eastern Plaguelands"] = { human = 2, forsaken = 2, troll = 1 },
    ["Hillsbrad Foothills"] = { human = 2, forsaken = 1, dwarf = 1 },
    ["The Hinterlands"] = { dwarf = 1, troll = 2, nightelf = 1 },
    ["Dun Morogh"] = { dwarf = 3, gnome = 3 },
    ["Searing Gorge"] = { dwarf = 2 },
    ["Burning Steppes"] = { dwarf = 1, orc = 2 },
    ["Elwynn Forest"] = { human = 3 },
    ["Deadwind Pass"] = { human = 1 },
    ["Duskwood"] = { human = 2 },
    ["Loch Modan"] = { dwarf = 2 },
    ["Redridge Mountains"] = { human = 2 },
    ["Stranglethorn Vale"] = { troll = 2, goblin = 1 },
    ["Swamp of Sorrows"] = { orc = 1 },
    ["Westfall"] = { human = 2 },
    ["Wetlands"] = { dwarf = 1, orc = 1 },
    ["Stormwind City"] = { human = 3, dwarf = 1, gnome = 1 },
    ["Ironforge"] = { dwarf = 3, gnome = 2 },
    ["Undercity"] = { forsaken = 3 },
    ["Gnomeregan"] = { gnome = 3 },
    ["Uldaman"] = { dwarf = 2 },
    ["Blackrock Depths"] = { dwarf = 3 },
    ["Shadowfang Keep"] = { human = 1, forsaken = 1 },
    ["Zul'Farrak"] = { troll = 3 },
    ["Zul'Gurub"] = { troll = 3 },
}

-- Environmental tags are intentionally orthogonal so personalities can like
-- broad concepts such as caves or graveyards without naming every location.
Loudmouth.ZoneVibeMetadata = {
    ["Durotar"] = { "arid", "canyon" },
    ["Mulgore"] = { "plains", "savanna", "mountain" },
    ["The Barrens"] = { "savanna", "arid" },
    ["Teldrassil"] = { "enchanted forest" },
    ["Darkshore"] = { "gloomy", "coast", "forest", "ruins" },
    ["Ashenvale"] = { "forest" },
    ["Thousand Needles"] = { "arid", "canyon" },
    ["Stonetalon Mountains"] = { "mountain", "forest" },
    ["Desolace"] = { "barren" },
    ["Feralas"] = { "forest", "jungle" },
    ["Dustwallow Marsh"] = { "swamp", "marsh" },
    ["Tanaris"] = { "desert" },
    ["Azshara"] = { "coast", "forest", "ruins", "arcane" },
    ["Felwood"] = { "corrupted forest", "fel", "demonic" },
    ["Un'Goro Crater"] = { "jungle", "swamp", "volcanic", "titan" },
    ["Moonglade"] = { "enchanted forest", "lake" },
    ["Silithus"] = { "desert", "insect", "old god", "twilight" },
    ["Winterspring"] = { "snow", "forest" },
    ["Orgrimmar"] = { "urban", "canyon" },
    ["Thunder Bluff"] = { "urban", "mesa", "plains" },
    ["Darnassus"] = { "urban", "enchanted forest" },
    ["Alterac Mountains"] = { "mountain", "snow", "ruins" },
    ["Arathi Highlands"] = { "highlands", "plains" },
    ["Badlands"] = { "badlands", "arid", "canyon" },
    ["Blasted Lands"] = { "badlands", "arid" },
    ["Tirisfal Glades"] = { "gloomy", "forest", "undead" },
    ["Silverpine Forest"] = { "gloomy", "forest", "undead" },
    ["Western Plaguelands"] = { "plague", "undead", "necromancy", "ruins", "farmland", "forest" },
    ["Eastern Plaguelands"] = { "plague", "undead", "necromancy", "ruins", "forest" },
    ["Hillsbrad Foothills"] = { "foothills", "farmland", "forest" },
    ["The Hinterlands"] = { "forest", "highlands" },
    ["Dun Morogh"] = { "snow", "mountain", "forest" },
    ["Searing Gorge"] = { "volcanic", "ash", "industrial" },
    ["Burning Steppes"] = { "volcanic", "ash", "mountain" },
    ["Elwynn Forest"] = { "forest", "pastoral", "farmland" },
    ["Deadwind Pass"] = { "barren", "canyon", "haunted", "arcane" },
    ["Duskwood"] = { "dark forest", "haunted", "undead" },
    ["Loch Modan"] = { "mountain", "lake", "forest" },
    ["Redridge Mountains"] = { "mountain", "lake", "forest" },
    ["Stranglethorn Vale"] = { "jungle", "ruins" },
    ["Swamp of Sorrows"] = { "swamp", "marsh", "gloomy" },
    ["Westfall"] = { "plains", "farmland" },
    ["Wetlands"] = { "swamp", "marsh" },
    ["Stormwind City"] = { "urban", "canals" },
    ["Ironforge"] = { "underground", "urban", "industrial", "forge" },
    ["Undercity"] = { "underground", "urban", "undead", "plague", "ruins", "alchemical" },
    ["Ragefire Chasm"] = { "cave", "volcanic", "demonic" },
    ["Wailing Caverns"] = { "cave", "corrupted", "nature" },
    ["The Deadmines"] = { "cave", "industrial" },
    ["Shadowfang Keep"] = { "gothic", "haunted", "undead", "worgen" },
    ["Blackfathom Deeps"] = { "cave", "ruins", "twilight", "naga" },
    ["The Stockade"] = { "prison", "underground", "urban" },
    ["Gnomeregan"] = { "underground", "industrial", "toxic" },
    ["Razorfen Kraul"] = { "cave", "quillboar" },
    ["Scarlet Monastery"] = { "gothic", "monastery" },
    ["Razorfen Downs"] = { "cave", "graveyard", "undead" },
    ["Uldaman"] = { "cave", "titan", "ruins" },
    ["Zul'Farrak"] = { "desert", "ruins" },
    ["Maraudon"] = { "cave", "corrupted", "nature" },
    ["The Temple of Atal'Hakkar"] = { "swamp", "ruins" },
    ["Blackrock Depths"] = { "underground", "volcanic", "industrial" },
    ["Blackrock Spire"] = { "underground", "volcanic" },
    ["Dire Maul"] = { "ruins" },
    ["Scholomance"] = { "gothic", "haunted", "undead", "necromancy" },
    ["Stratholme"] = { "ruined city", "undead", "plague" },
    ["Molten Core"] = { "cave", "volcanic", "elemental" },
    ["Onyxia's Lair"] = { "cave", "dragon" },
    ["Blackwing Lair"] = { "cave", "volcanic", "dragon" },
    ["Zul'Gurub"] = { "jungle", "ruins" },
    ["Ruins of Ahn'Qiraj"] = { "desert", "ruins", "insect", "old god" },
    ["Ahn'Qiraj"] = { "underground", "ruins", "insect", "old god" },
    ["Naxxramas"] = { "undead", "necromancy" },
}

Loudmouth.SubzoneRaceMetadata = {
    ["Mulgore"] = { ["Bael'dun Digsite"] = { dwarf = 2 } },
    ["The Barrens"] = { ["Bael Modan"] = { dwarf = 2 } },
    ["Thousand Needles"] = { ["Rustmaul Dig Site"] = { dwarf = 2 }, ["The Shimmering Flats"] = { gnome = 1 } },
    ["Dustwallow Marsh"] = { ["Bael'dun Keep"] = { dwarf = 2 } },
    ["Silithus"] = { ["Bronzebeard Encampment"] = { dwarf = 2 } },
    ["Hillsbrad Foothills"] = { ["Dun Garok"] = { dwarf = 2 } },
    ["Badlands"] = {
        ["Angor Fortress"] = { dwarf = 3 },
        ["Uldaman"] = { dwarf = 2 },
        ["Hammertoe's Digsite"] = { dwarf = 1 },
    },
    ["Wetlands"] = {
        ["Whelgar's Excavation Site"] = { dwarf = 2 },
        ["Dun Modr"] = { dwarf = 2 },
        ["Ironbeard's Tomb"] = { dwarf = 2 },
        ["Dun Algaz"] = { dwarf = 2 },
    },
    ["Dun Morogh"] = { ["Gnomeregan"] = { gnome = 3 } },
    ["Ironforge"] = { ["Tinker Town"] = { gnome = 3 }, ["Hall of Explorers"] = { dwarf = 3 } },
    ["The Hinterlands"] = { ["Aerie Peak"] = { dwarf = 3 }, ["Wildhammer Keep"] = { dwarf = 3 } },
    ["Searing Gorge"] = { ["The Slag Pit"] = { dwarf = 3 }, ["Thorium Point"] = { dwarf = 2 } },
    ["Burning Steppes"] = { ["Ruins of Thaurissan"] = { dwarf = 3 } },
    ["Stormwind City"] = { ["Dwarven District"] = { dwarf = 2 } },
}

Loudmouth.SubzoneVibeMetadata = {
    ["Durotar"] = {
        ["Skull Rock"] = { "cave" },
        ["Dustwind Cave"] = { "cave" },
        ["Darkspear Strand"] = { "coast" },
        ["Echo Isles"] = { "coast" },
    },
    ["The Barrens"] = {
        ["Boulder Lode Mine"] = { "cave" },
        ["The Venture Co. Mine"] = { "cave", "industrial" },
        ["Dreadmist Den"] = { "cave" },
        ["The Forgotten Pools"] = { "oasis" },
        ["Lushwater Oasis"] = { "oasis" },
        ["The Stagnant Oasis"] = { "oasis" },
    },
    ["Teldrassil"] = {
        ["Shadowthread Cave"] = { "cave" },
        ["Fel Rock"] = { "cave", "demonic", "fel" },
        ["Ban'ethil Barrow Den"] = { "cave", "corrupted" },
    },
    ["Darkshore"] = {
        ["Ameth'Aran"] = { "ruins", "undead", "haunted" },
        ["Bashal'Aran"] = { "ruins", "undead", "haunted" },
    },
    ["Ashenvale"] = {
        ["Talondeep Path"] = { "cave", "underground" },
        ["Felfire Hill"] = { "fel", "demonic", "corrupted" },
        ["Demon Fall Canyon"] = { "demonic", "corrupted" },
        ["Demon Fall Ridge"] = { "demonic", "corrupted" },
        ["Satyrnaar"] = { "ruins", "demonic", "corrupted" },
    },
    ["Thousand Needles"] = {
        ["Roguefeather Den"] = { "cave" },
        ["Splithoof Crag"] = { "cave" },
    },
    ["Stonetalon Mountains"] = {
        ["Boulderslide Ravine"] = { "cave" },
        ["Windshear Mine"] = { "cave", "industrial" },
        ["The Charred Vale"] = { "charred" },
    },
    ["Desolace"] = {
        ["Kodo Graveyard"] = { "graveyard", "bones" },
        ["Mannoroc Coven"] = { "demonic", "fel", "warlock" },
        ["Sargeron"] = { "demonic", "ruins" },
    },
    ["Feralas"] = {
        ["The Writhing Deep"] = { "cave", "insect" },
        ["Dire Maul"] = { "ruins", "arcane", "demonic" },
        ["Ruins of Isildien"] = { "ruins" },
        ["Ruins of Ravenwind"] = { "ruins" },
    },
    ["Dustwallow Marsh"] = {
        ["The Den of Flame"] = { "cave" },
        ["Darkmist Cavern"] = { "cave" },
        ["Tidefury Cove"] = { "coast" },
    },
    ["Tanaris"] = {
        ["Caverns of Time"] = { "cave", "titan", "dragon" },
        ["Steamwheedle Port"] = { "coast" },
        ["Lost Rigger Cove"] = { "coast", "pirate" },
        ["Eastmoon Ruins"] = { "ruins" },
        ["Southmoon Ruins"] = { "ruins" },
    },
    ["Felwood"] = {
        ["Jaedenar"] = { "demonic", "fel", "corrupted" },
        ["Shadow Hold"] = { "cave", "underground", "demonic", "fel" },
        ["Shrine of the Deceiver"] = { "demonic", "fel" },
        ["Shatter Scar Vale"] = { "demonic", "fel", "corrupted" },
        ["Jadefire Run"] = { "demonic", "fel" },
        ["Irontree Cavern"] = { "cave" },
        ["Ruins of Constellas"] = { "ruins" },
    },
    ["Un'Goro Crater"] = {
        ["Fungal Rock"] = { "cave" },
        ["The Slithering Scar"] = { "cave", "insect" },
    },
    ["Silithus"] = {
        ["Hive'Ashi"] = { "cave", "insect" },
        ["Hive'Zora"] = { "cave", "insect" },
        ["Hive'Regal"] = { "cave", "insect" },
        ["Southwind Village"] = { "ruins" },
    },
    ["Winterspring"] = {
        ["Mazthoril"] = { "cave", "dragon", "arcane" },
        ["Darkwhisper Gorge"] = { "cave", "demonic", "fel" },
    },
    ["Orgrimmar"] = {
        ["Cleft of Shadow"] = { "underground", "demonic", "warlock" },
    },
    ["Arathi Highlands"] = {
        ["Stromgarde Keep"] = { "ruins" },
    },
    ["Badlands"] = {
        ["Dustbelch Grotto"] = { "cave" },
        ["Uldaman"] = { "cave", "ruins", "titan" },
        ["Agmond's End"] = { "ruins", "titan" },
        ["Hammertoe's Digsite"] = { "ruins", "titan" },
    },
    ["Blasted Lands"] = {
        ["The Tainted Scar"] = { "fel", "demonic", "corrupted" },
        ["The Dark Portal"] = { "demonic", "fel", "ruins" },
        ["Altar of Storms"] = { "demonic", "warlock" },
    },
    ["Tirisfal Glades"] = {
        ["The Deathknell Graves"] = { "graveyard", "undead", "haunted" },
        ["Shadow Grave"] = { "graveyard", "undead" },
        ["Faol's Rest"] = { "graveyard", "haunted" },
        ["Agamand Mills"] = { "graveyard", "undead", "haunted" },
        ["Garren's Haunt"] = { "undead", "haunted" },
        ["Ruins of Lordaeron"] = { "ruins", "undead", "haunted" },
    },
    ["Silverpine Forest"] = {
        ["The Sepulcher"] = { "graveyard", "undead" },
        ["Fenris Isle"] = { "ruins", "undead", "haunted" },
        ["Pyrewood Village"] = { "worgen", "haunted" },
        ["Shadowfang Keep"] = { "worgen", "undead", "haunted" },
    },
    ["Western Plaguelands"] = {
        ["School of Necromancy"] = { "necromancy", "undead", "haunted" },
        ["Sorrow Hill"] = { "graveyard", "undead" },
        ["The Weeping Cave"] = { "cave", "plague" },
        ["Caer Darrow"] = { "ruins", "undead", "haunted", "necromancy" },
    },
    ["Hillsbrad Foothills"] = {
        ["Purgation Isle"] = { "undead", "haunted" },
        ["Dalaran"] = { "ruins", "arcane" },
        ["Ruins of Alterac"] = { "ruins" },
    },
    ["The Hinterlands"] = {
        ["Skulk Rock"] = { "cave" },
        ["Jintha'Alor"] = { "ruins" },
        ["The Altar of Zul"] = { "ruins" },
    },
    ["Dun Morogh"] = {
        ["Frostmane Hold"] = { "cave" },
        ["The Grizzled Den"] = { "cave" },
        ["Gol'Bolar Quarry"] = { "cave", "industrial" },
        ["Steelgrill's Depot"] = { "industrial" },
        ["Gnomeregan"] = { "underground", "industrial", "toxic" },
    },
    ["Searing Gorge"] = {
        ["The Slag Pit"] = { "cave", "industrial" },
        ["Blackchar Cave"] = { "cave" },
    },
    ["Burning Steppes"] = {
        ["Dreadmaul Rock"] = { "demonic" },
        ["Altar of Storms"] = { "demonic", "warlock" },
        ["Ruins of Thaurissan"] = { "ruins" },
        ["Terror Wing Path"] = { "dragon" },
    },
    ["Deadwind Pass"] = {
        ["The Vice"] = { "cave", "demonic" },
        ["Morgan's Plot"] = { "graveyard", "undead", "haunted" },
        ["Karazhan"] = { "ruins", "haunted", "arcane", "demonic" },
    },
    ["Duskwood"] = {
        ["Raven Hill"] = { "ruins", "undead", "haunted" },
        ["Raven Hill Cemetery"] = { "graveyard", "undead", "haunted" },
        ["Tranquil Gardens Cemetery"] = { "graveyard", "haunted" },
        ["Dawning Wood Catacombs"] = { "crypt", "cave", "undead", "haunted" },
        ["Roland's Doom"] = { "cave", "worgen", "haunted" },
        ["Vul'Gol Ogre Mound"] = { "cave" },
    },
    ["Loch Modan"] = {
        ["Silver Stream Mine"] = { "cave" },
        ["Stonesplinter Valley"] = { "cave" },
    },
    ["Redridge Mountains"] = {
        ["Rethban Caverns"] = { "cave" },
        ["Render's Rock"] = { "cave" },
        ["Stonewatch"] = { "ruins" },
    },
    ["Stranglethorn Vale"] = {
        ["Crystalvein Mine"] = { "cave" },
        ["Nek'mani Wellspring"] = { "cave" },
        ["Booty Bay"] = { "coast", "pirate", "urban" },
        ["The Wild Shore"] = { "coast", "pirate" },
    },
    ["Swamp of Sorrows"] = {
        ["Itharius's Cave"] = { "cave" },
        ["Stagalbog Cave"] = { "cave" },
    },
    ["Westfall"] = {
        ["Gold Coast Quarry"] = { "cave" },
        ["Jangolode Mine"] = { "cave" },
        ["Longshore"] = { "coast" },
        ["Moonbrook"] = { "ruins" },
    },
    ["Wetlands"] = {
        ["Thelgen Rock"] = { "cave" },
        ["Whelgar's Excavation Site"] = { "cave", "ruins", "titan" },
        ["Menethil Harbor"] = { "coast" },
        ["Dun Modr"] = { "ruins" },
    },
    ["Stormwind City"] = {
        ["The Slaughtered Lamb"] = { "warlock", "demonic", "urban" },
        ["Mage Quarter"] = { "arcane", "warlock", "urban" },
    },
    ["Scarlet Monastery"] = {
        ["Chamber of Atonement"] = { "graveyard", "undead", "haunted" },
        ["Forlorn Cloister"] = { "graveyard", "undead", "haunted" },
        ["Honor's Tomb"] = { "graveyard", "undead", "haunted" },
    },
    ["The Temple of Atal'Hakkar"] = {
        ["Chamber of the Dreamer"] = { "dragon" },
    },
    ["Blackrock Spire"] = {
        ["Dragonspire Hall"] = { "dragon" },
        ["The Rookery"] = { "dragon" },
        ["Spire Throne"] = { "dragon" },
    },
    ["Dire Maul"] = {
        ["Warpwood Quarter"] = { "forest", "demonic", "corrupted" },
        ["The Conservatory"] = { "forest", "demonic", "corrupted" },
        ["Capital Gardens"] = { "arcane", "undead", "haunted" },
        ["Court of the Highborne"] = { "arcane", "undead", "haunted" },
        ["Prison of Immol'thar"] = { "arcane", "demonic" },
    },
    ["Naxxramas"] = {
        ["Plague Quarter"] = { "plague" },
    },
}
